name: Produce Vernuntii artifact
description: Produces an artifact containing a .nupkg representing the dotnet cli tool for Vernuntii

inputs:
  artifact-name:
    description: The name of produced artifact
    required: true
  console-tool-project-name:
    description: The project name of console tool
    required: true
  msbuild-integration-project-name:
    description: The project name of msbuild integration
    required: true
  msbuild-verbosity:
    description: MSBuild verbosity
    required: true
  msbuild-configuration:
    description: MSBuild configuration
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Pack msbuild project
      shell: bash
      run: |
        PROJECTS=(
          './src/${{ inputs.console-tool-project-name }}/${{ inputs.console-tool-project-name }}.csproj'
          './src/${{ inputs.msbuild-integration-project-name }}/${{ inputs.msbuild-integration-project-name }}.csproj'
        )

        for PROJECT in "${PROJECTS[@]}"
        do
          dotnet pack $PROJECT \
          --verbosity ${{ inputs.msbuild-verbosity }} \
          --configuration ${{ inputs.msbuild-configuration }} \
          --output ~/artifacts
        done

    - name: Upload Vernuntii (artifacts)
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ~/artifacts/*.nupkg
        if-no-files-found: error
